services:
  quiz-app:
    image: prasansrini29/quiz-app:latest
    container_name: quiz-app
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://quiz-db:3306/student_tracker
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=prasanna@123
    ports:
      - 8888:8888
    depends_on:
      - quiz-db
  kafka-demo-app:
    image: prasansrini29/kafka-docker-demo:latest
    container_name: kafka-demo-app
    ports:
      - 8090:8090
    depends_on:
      - quiz-app
  quiz-db:
    image: mysql:8.0.27
    container_name: quiz-db
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=student_tracker
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db-password
    ports:
      - 3306:3306
volumes:
  db-data:
secrets:
  db-password:
    file: db/password.txt